### ISSUE TITLE
Sender email and Sender password needs to be secured

### ISSUE THREAD

**Issue by abmazhr** [SalmaAhmed20/Crowd-Funding-App-Python#1]
@SalmaAhmed20 Amazing work on this example 🤩🤩🤩, and if you don't mind pushing a small comment here so it would be as this,
Sender's email and password are sensitive information so we may get them from a secret manager or at least fetch them as ENV Vars from the Operating System (OS) to be hidden from the source code files, what do you think? that would be better.? 😊

so instead of using `sender_email = "ur email"` we can be using this
```python
from os import environ
sender_email = environ.get("SENDER_EMAIL",  None)
assert sender_email is not None, "Failed to get SENDER_EMAIL from ENV VARS"
```
the same in here, instead of using `password = "ur email password"` we can be using 
```python
from os import environ
password = environ.get("PASSWORD",  None)
assert password is not None, "Failed to get PASSWORD from ENV VARS"
```

**Comment by SalmaAhmed20** [comment]
thanks for the advice! I really appreciate you for sharing and contributing I will fix the issue to be more secure

**Comment by abmazhr** [comment]
@SalmaAhmed20 thank you so much, really it's my pleasure and appreciate that so much 😊
